exclude = ["notebooks", "data", "outputs"]
line-length = 100
target-version = "py311"

[lint]
select = ["E", "F", "W", "I", "UP", "B", "C4"]
ignore = ["E501", "B008", "UP017"]

[lint.per-file-ignores]
"tests/*" = ["E402"]
"streaming/spark_consumer.py" = ["E402"]
